/**
 * Api test
 * 一个简单的测试
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Stock {
    id?: number;
    name: string;
    price?: string;
    rating?: number;
    desc?: string;
    categories?: Array<string>;
}
